[project]
name = "robot-data-generator"
version = "0.1.0"
description = "Robot simulation data generation package - environments, poses, and trajectories"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "numpy>=1.24.4",
    "matplotlib>=3.5.0",
    "scipy>=1.10.1",
    "pyyaml>=6.0",
    "plyfile>=1.0.0",
    "ompl",
    "box2d>=2.3.10",  # for collision detection
    "joblib>=1.4.2",  # for parallel processing
    "torch>=2.0.0",   # for SE(3) trajectory processing
    "h5py>=3.8.0",    # for HDF5 trajectory data
]

[project.optional-dependencies]
dev = [
    "ipykernel>=6.29.5",
    "ipython>=8.12.3",
    "jupyter-client>=8.6.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pose", "pointcloud", "reference_planner", "config"]
