# SE(3) Riemannian Flow Matching Configuration
# Complete configuration for training and evaluation

# Experiment configuration
experiment_name: "se3_rfm_baseline"
exp_dir: "./experiments"
use_wandb: true
seed: 42
use_amp: true  # Mixed precision training

# Wandb configuration
wandb:
  project: "se3-rfm-robotics"
  entity: null  # Set your wandb entity
  name: null    # Will use experiment_name if null
  tags: ["se3", "rfm", "obstacle_avoidance", "robotics"]

# Model configuration
model:
  # Point cloud encoder (DGCNN-based, like fm-main)
  point_cloud_encoder:
    k: 20                    # KNN neighbors
    emb_dims: 1024          # Embedding dimensions  
    dropout: 0.5            # Output: emb_dims*2 = 2048

  # Robot geometry encoder (ellipsoid parameters)
  geometry_encoder:
    input_dim: 3            # (a, b, c) ellipsoid semi-axes
    hidden_dim: 64
    output_dim: 32

  # SE(3) pose encoder (simple flatten like fm-main)
  # No config needed - just flattens SE(3) to 12 dimensions

  # Velocity field network  
  velocity_field_config:
    input_dim: 2105         # current(12) + target(12) + pc(2048) + geom(32) + time(1)
    hidden_dims: [2048, 1024, 512, 512, 512]  # Like fm-main
    output_dim: 6           # SE(3) twist vector
    dropout: 0.1

  # Flow matching configuration
  prob_path: "OT"          # "OT" or "OT_CFM"
  
  # Initial distribution for sampling
  init_dist:
    type: "uniform"         # "uniform" or "gaussian"
    std: 0.1               # For gaussian

  # ODE solver configuration
  ode_solver:
    type: "rk4"            # "euler", "rk4", "adaptive"
    n_steps: 20

# Data configuration
data:
  train:
    data_root: "data/trajectories"
    batch_size: 16
    num_workers: 8
    max_trajectories: null    # Load all available
    augment_data: true
    use_bsplined: true        # Use B-spline smoothed trajectories
    subsample_factor: 1       # Trajectory subsampling

  val:
    data_root: "data/trajectories"  
    batch_size: 8
    num_workers: 4
    max_trajectories: 100     # Limit validation set size
    augment_data: false
    use_bsplined: true
    subsample_factor: 2       # More subsampling for validation

# Training configuration
training:
  num_epochs: 1000
  log_interval: 50          # Steps between training logs
  val_interval: 500         # Steps between validation
  save_interval: 2000       # Steps between checkpoints
  vis_interval: 1000        # Steps between visualizations

  # Loss function configuration
  loss:
    flow_matching_weight: 1.0
    collision_weight: 0.1
    regularization_weight: 0.01
    
    # Flow matching loss config
    flow_matching:
      prob_path: "OT"
      noise_scale: 0.01
      weight_linear: 1.0
      weight_angular: 1.0
      
    # Collision loss config  
    collision:
      collision_threshold: 0.05
      penalty_scale: 1.0
      use_soft_penalty: true
      
    # Regularization loss config
    regularization:
      smoothness_weight: 0.1
      velocity_weight: 0.01
      acceleration_weight: 0.01

  # Optimizer configuration
  optimizer:
    type: "adamw"
    lr: 0.0005
    weight_decay: 0.0001
    betas: [0.9, 0.999]
    eps: 1e-8

  # Learning rate scheduler
  scheduler:
    type: "cosine_annealing"
    T_max: 1000              # Number of epochs for full cycle
    eta_min: 1e-6           # Minimum learning rate
    
    # Alternative: step scheduler
    # type: "step"
    # step_size: 200
    # gamma: 0.5
    
    # Alternative: exponential scheduler  
    # type: "exponential"
    # gamma: 0.99

# Evaluation configuration
evaluation:
  # Trajectory generation settings
  n_test_trajectories: 50
  ode_steps: [10, 20, 50]    # Different step sizes to test
  
  # Metrics to compute
  metrics:
    - "success_rate"         # Collision-free trajectories
    - "path_length"          # Total path length
    - "smoothness"           # Trajectory smoothness
    - "efficiency"           # Path optimality
    - "computation_time"     # Generation time
    - "nfe_count"           # Number of function evaluations
  
  # Visualization settings
  save_trajectories: true
  save_visualizations: true
  max_vis_trajectories: 10

# Model architecture sizes (updated like fm-main)
# Point cloud: [B, N, 3] -> [B, 2048] (emb_dims*2)
# Geometry: [B, 3] -> [B, 32] 
# SE(3) pose: [B, 4, 4] -> [B, 12] (direct flatten)
# Combined: [B, 12*2 + 2048 + 32 + 1] = [B, 2105] -> [B, 6]

# Hardware configuration
device: "cuda"
num_gpus: 1                 # Set to >1 for distributed training
precision: "float32"       # "float16" for mixed precision

# Debugging and development
debug_mode: false
profile_training: false
save_memory: true